var annotated_dup =
[
    [ "heffte", "namespaceheffte.html", [
      [ "backend", "namespaceheffte_1_1backend.html", [
        [ "is_enabled< cufft >", "structheffte_1_1backend_1_1is__enabled_3_01cufft_01_4.html", null ],
        [ "is_enabled< cufft_cos >", "structheffte_1_1backend_1_1is__enabled_3_01cufft__cos_01_4.html", null ],
        [ "is_enabled< cufft_sin >", "structheffte_1_1backend_1_1is__enabled_3_01cufft__sin_01_4.html", null ],
        [ "device_instance< tag::gpu >", "structheffte_1_1backend_1_1device__instance_3_01tag_1_1gpu_01_4.html", "structheffte_1_1backend_1_1device__instance_3_01tag_1_1gpu_01_4" ],
        [ "default_backend< tag::gpu >", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1gpu_01_4.html", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1gpu_01_4" ],
        [ "data_manipulator< tag::gpu >", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1gpu_01_4.html", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1gpu_01_4" ],
        [ "buffer_traits< cufft >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01cufft_01_4" ],
        [ "buffer_traits< cufft_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__cos_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__cos_01_4" ],
        [ "buffer_traits< cufft_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__sin_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__sin_01_4" ],
        [ "is_enabled< fftw >", "structheffte_1_1backend_1_1is__enabled_3_01fftw_01_4.html", null ],
        [ "is_enabled< fftw_cos >", "structheffte_1_1backend_1_1is__enabled_3_01fftw__cos_01_4.html", null ],
        [ "is_enabled< fftw_sin >", "structheffte_1_1backend_1_1is__enabled_3_01fftw__sin_01_4.html", null ],
        [ "is_enabled< mkl >", "structheffte_1_1backend_1_1is__enabled_3_01mkl_01_4.html", null ],
        [ "is_enabled< mkl_cos >", "structheffte_1_1backend_1_1is__enabled_3_01mkl__cos_01_4.html", null ],
        [ "is_enabled< mkl_sin >", "structheffte_1_1backend_1_1is__enabled_3_01mkl__sin_01_4.html", null ],
        [ "default_backend< tag::cpu >", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1cpu_01_4.html", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1cpu_01_4" ],
        [ "is_enabled< onemkl >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl_01_4.html", null ],
        [ "is_enabled< onemkl_cos >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl__cos_01_4.html", null ],
        [ "is_enabled< onemkl_sin >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl__sin_01_4.html", null ],
        [ "buffer_traits< onemkl >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl_01_4" ],
        [ "buffer_traits< onemkl_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__cos_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__cos_01_4" ],
        [ "buffer_traits< onemkl_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__sin_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__sin_01_4" ],
        [ "is_enabled< rocfft >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft_01_4.html", null ],
        [ "is_enabled< rocfft_cos >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft__cos_01_4.html", null ],
        [ "is_enabled< rocfft_sin >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft__sin_01_4.html", null ],
        [ "buffer_traits< rocfft >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft_01_4" ],
        [ "buffer_traits< rocfft_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__cos_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__cos_01_4" ],
        [ "buffer_traits< rocfft_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__sin_01_4.html", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__sin_01_4" ],
        [ "is_enabled< stock >", "structheffte_1_1backend_1_1is__enabled_3_01stock_01_4.html", null ],
        [ "is_enabled< stock_cos >", "structheffte_1_1backend_1_1is__enabled_3_01stock__cos_01_4.html", null ],
        [ "is_enabled< stock_sin >", "structheffte_1_1backend_1_1is__enabled_3_01stock__sin_01_4.html", null ],
        [ "data_manipulator", "structheffte_1_1backend_1_1data__manipulator.html", null ],
        [ "data_manipulator< tag::cpu >", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1cpu_01_4.html", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1cpu_01_4" ],
        [ "fftw", "structheffte_1_1backend_1_1fftw.html", null ],
        [ "fftw_cos", "structheffte_1_1backend_1_1fftw__cos.html", null ],
        [ "fftw_sin", "structheffte_1_1backend_1_1fftw__sin.html", null ],
        [ "stock", "structheffte_1_1backend_1_1stock.html", null ],
        [ "stock_cos", "structheffte_1_1backend_1_1stock__cos.html", null ],
        [ "stock_sin", "structheffte_1_1backend_1_1stock__sin.html", null ],
        [ "mkl", "structheffte_1_1backend_1_1mkl.html", null ],
        [ "mkl_cos", "structheffte_1_1backend_1_1mkl__cos.html", null ],
        [ "mkl_sin", "structheffte_1_1backend_1_1mkl__sin.html", null ],
        [ "cufft", "structheffte_1_1backend_1_1cufft.html", null ],
        [ "cufft_cos", "structheffte_1_1backend_1_1cufft__cos.html", null ],
        [ "cufft_sin", "structheffte_1_1backend_1_1cufft__sin.html", null ],
        [ "rocfft", "structheffte_1_1backend_1_1rocfft.html", null ],
        [ "rocfft_cos", "structheffte_1_1backend_1_1rocfft__cos.html", null ],
        [ "rocfft_sin", "structheffte_1_1backend_1_1rocfft__sin.html", null ],
        [ "onemkl", "structheffte_1_1backend_1_1onemkl.html", null ],
        [ "onemkl_cos", "structheffte_1_1backend_1_1onemkl__cos.html", null ],
        [ "onemkl_sin", "structheffte_1_1backend_1_1onemkl__sin.html", null ],
        [ "is_enabled", "structheffte_1_1backend_1_1is__enabled.html", null ],
        [ "buffer_traits", "structheffte_1_1backend_1_1buffer__traits.html", "structheffte_1_1backend_1_1buffer__traits" ],
        [ "uses_gpu", "structheffte_1_1backend_1_1uses__gpu.html", null ],
        [ "uses_gpu< backend_tag, typename std::enable_if< std::is_same< typename buffer_traits< backend_tag >::location, tag::gpu >::value, void >::type >", "structheffte_1_1backend_1_1uses__gpu_3_01backend__tag_00_01typename_01std_1_1enable__if_3_01std_6bad166a1b2e2b72cd8ee197f3565dff.html", null ],
        [ "device_instance", "structheffte_1_1backend_1_1device__instance.html", "structheffte_1_1backend_1_1device__instance" ],
        [ "default_backend", "structheffte_1_1backend_1_1default__backend.html", "structheffte_1_1backend_1_1default__backend" ],
        [ "uses_fft_types", "structheffte_1_1backend_1_1uses__fft__types.html", null ],
        [ "check_types", "structheffte_1_1backend_1_1check__types.html", null ],
        [ "check_types< backend_tag, input, output, typename std::enable_if< uses_fft_types< backend_tag >::value and((std::is_same< input, float >::value and is_ccomplex< output >::value) or(std::is_same< input, double >::value and is_zcomplex< output >::value) or(is_ccomplex< input >::value and is_ccomplex< output >::value) or(is_zcomplex< input >::value and is_zcomplex< output >::value))>::type >", "structheffte_1_1backend_1_1check__types_3_01backend__tag_00_01input_00_01output_00_01typename_01c412e8b081eebe81d371306e70d2da56.html", null ],
        [ "uses_fft_types< fftw_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01fftw__cos_01_4.html", null ],
        [ "uses_fft_types< fftw_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01fftw__sin_01_4.html", null ],
        [ "uses_fft_types< stock_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01stock__cos_01_4.html", null ],
        [ "uses_fft_types< stock_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01stock__sin_01_4.html", null ],
        [ "uses_fft_types< mkl_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01mkl__cos_01_4.html", null ],
        [ "uses_fft_types< mkl_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01mkl__sin_01_4.html", null ],
        [ "uses_fft_types< cufft_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01cufft__cos_01_4.html", null ],
        [ "uses_fft_types< cufft_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01cufft__sin_01_4.html", null ],
        [ "uses_fft_types< rocfft_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01rocfft__cos_01_4.html", null ],
        [ "uses_fft_types< rocfft_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01rocfft__sin_01_4.html", null ],
        [ "uses_fft_types< onemkl_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01onemkl__cos_01_4.html", null ],
        [ "uses_fft_types< onemkl_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01onemkl__sin_01_4.html", null ],
        [ "check_types< backend_tag, input, output, typename std::enable_if< not uses_fft_types< backend_tag >::value and((std::is_same< input, float >::value and std::is_same< output, float >::value) or(std::is_same< input, double >::value and std::is_same< output, double >::value))>::type >", "structheffte_1_1backend_1_1check__types_3_01backend__tag_00_01input_00_01output_00_01typename_01f9006ec2132705c3597d1dc98451f7b8.html", null ]
      ] ],
      [ "cuda", "namespaceheffte_1_1cuda.html", [
        [ "cos_pre_pos_processor", "structheffte_1_1cuda_1_1cos__pre__pos__processor.html", null ],
        [ "sin_pre_pos_processor", "structheffte_1_1cuda_1_1sin__pre__pos__processor.html", null ]
      ] ],
      [ "gpu", null, [
        [ "magma_handle", "structheffte_1_1gpu_1_1magma__handle.html", "structheffte_1_1gpu_1_1magma__handle" ],
        [ "magma_handle< tag::gpu >", "structheffte_1_1gpu_1_1magma__handle_3_01tag_1_1gpu_01_4.html", "structheffte_1_1gpu_1_1magma__handle_3_01tag_1_1gpu_01_4" ]
      ] ],
      [ "oapi", "namespaceheffte_1_1oapi.html", [
        [ "cos_pre_pos_processor", "structheffte_1_1oapi_1_1cos__pre__pos__processor.html", null ],
        [ "sin_pre_pos_processor", "structheffte_1_1oapi_1_1sin__pre__pos__processor.html", null ]
      ] ],
      [ "rocm", "namespaceheffte_1_1rocm.html", [
        [ "cos_pre_pos_processor", "structheffte_1_1rocm_1_1cos__pre__pos__processor.html", null ],
        [ "sin_pre_pos_processor", "structheffte_1_1rocm_1_1sin__pre__pos__processor.html", null ]
      ] ],
      [ "stock", null, [
        [ "biFuncNode", "structheffte_1_1stock_1_1biFuncNode.html", "structheffte_1_1stock_1_1biFuncNode" ],
        [ "omega", "structheffte_1_1stock_1_1omega.html", null ],
        [ "Fourier_Transform", "classheffte_1_1stock_1_1Fourier__Transform.html", "classheffte_1_1stock_1_1Fourier__Transform" ],
        [ "complex_allocator_t", "classheffte_1_1stock_1_1complex__allocator__t.html", "classheffte_1_1stock_1_1complex__allocator__t" ],
        [ "Complex", "classheffte_1_1stock_1_1Complex.html", "classheffte_1_1stock_1_1Complex" ],
        [ "is_real", "structheffte_1_1stock_1_1is__real.html", null ],
        [ "is_complex", "structheffte_1_1stock_1_1is__complex.html", null ],
        [ "pack", "structheffte_1_1stock_1_1pack.html", null ],
        [ "pack< float, 1 >", "structheffte_1_1stock_1_1pack_3_01float_00_011_01_4.html", "structheffte_1_1stock_1_1pack_3_01float_00_011_01_4" ],
        [ "pack< double, 1 >", "structheffte_1_1stock_1_1pack_3_01double_00_011_01_4.html", "structheffte_1_1stock_1_1pack_3_01double_00_011_01_4" ]
      ] ],
      [ "tag", "namespaceheffte_1_1tag.html", [
        [ "cpu", "structheffte_1_1tag_1_1cpu.html", null ],
        [ "gpu", "structheffte_1_1tag_1_1gpu.html", null ]
      ] ],
      [ "is_ccomplex< cufftComplex >", "structheffte_1_1is__ccomplex_3_01cufftComplex_01_4.html", null ],
      [ "is_zcomplex< cufftDoubleComplex >", "structheffte_1_1is__zcomplex_3_01cufftDoubleComplex_01_4.html", null ],
      [ "plan_cufft", "structheffte_1_1plan__cufft.html", "structheffte_1_1plan__cufft" ],
      [ "cufft_executor", "classheffte_1_1cufft__executor.html", "classheffte_1_1cufft__executor" ],
      [ "plan_cufft_r2c", "structheffte_1_1plan__cufft__r2c.html", "structheffte_1_1plan__cufft__r2c" ],
      [ "cufft_executor_r2c", "classheffte_1_1cufft__executor__r2c.html", "classheffte_1_1cufft__executor__r2c" ],
      [ "one_dim_backend< backend::cufft >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft_01_4" ],
      [ "one_dim_backend< backend::cufft_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__cos_01_4" ],
      [ "one_dim_backend< backend::cufft_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__sin_01_4" ],
      [ "direct_packer< tag::gpu >", "structheffte_1_1direct__packer_3_01tag_1_1gpu_01_4.html", "structheffte_1_1direct__packer_3_01tag_1_1gpu_01_4" ],
      [ "transpose_packer< tag::gpu >", "structheffte_1_1transpose__packer_3_01tag_1_1gpu_01_4.html", "structheffte_1_1transpose__packer_3_01tag_1_1gpu_01_4" ],
      [ "default_plan_options< backend::cufft >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft_01_4.html", null ],
      [ "default_plan_options< backend::cufft_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft__cos_01_4.html", null ],
      [ "default_plan_options< backend::cufft_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft__sin_01_4.html", null ],
      [ "is_ccomplex< fftwf_complex >", "structheffte_1_1is__ccomplex_3_01fftwf__complex_01_4.html", null ],
      [ "is_zcomplex< fftw_complex >", "structheffte_1_1is__zcomplex_3_01fftw__complex_01_4.html", null ],
      [ "plan_fftw", "structheffte_1_1plan__fftw.html", null ],
      [ "plan_fftw< std::complex< float >, dir >", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01float_01_4_00_01dir_01_4.html", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01float_01_4_00_01dir_01_4" ],
      [ "plan_fftw< std::complex< double >, dir >", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01double_01_4_00_01dir_01_4.html", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01double_01_4_00_01dir_01_4" ],
      [ "fftw_executor", "classheffte_1_1fftw__executor.html", "classheffte_1_1fftw__executor" ],
      [ "plan_fftw< float, dir >", "structheffte_1_1plan__fftw_3_01float_00_01dir_01_4.html", "structheffte_1_1plan__fftw_3_01float_00_01dir_01_4" ],
      [ "plan_fftw< double, dir >", "structheffte_1_1plan__fftw_3_01double_00_01dir_01_4.html", "structheffte_1_1plan__fftw_3_01double_00_01dir_01_4" ],
      [ "fftw_executor_r2c", "classheffte_1_1fftw__executor__r2c.html", "classheffte_1_1fftw__executor__r2c" ],
      [ "one_dim_backend< backend::fftw >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw_01_4" ],
      [ "one_dim_backend< backend::fftw_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__cos_01_4" ],
      [ "one_dim_backend< backend::fftw_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__sin_01_4" ],
      [ "default_plan_options< backend::fftw >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw_01_4.html", null ],
      [ "default_plan_options< backend::fftw_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw__cos_01_4.html", null ],
      [ "default_plan_options< backend::fftw_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw__sin_01_4.html", null ],
      [ "is_ccomplex< float _Complex >", "structheffte_1_1is__ccomplex_3_01float_01__Complex_01_4.html", null ],
      [ "is_zcomplex< double _Complex >", "structheffte_1_1is__zcomplex_3_01double_01__Complex_01_4.html", null ],
      [ "plan_mkl", "structheffte_1_1plan__mkl.html", "structheffte_1_1plan__mkl" ],
      [ "mkl_executor", "classheffte_1_1mkl__executor.html", "classheffte_1_1mkl__executor" ],
      [ "plan_mkl_r2c", "structheffte_1_1plan__mkl__r2c.html", "structheffte_1_1plan__mkl__r2c" ],
      [ "mkl_executor_r2c", "classheffte_1_1mkl__executor__r2c.html", "classheffte_1_1mkl__executor__r2c" ],
      [ "one_dim_backend< backend::mkl >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl_01_4" ],
      [ "one_dim_backend< backend::mkl_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__cos_01_4" ],
      [ "one_dim_backend< backend::mkl_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__sin_01_4" ],
      [ "default_plan_options< backend::mkl >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl_01_4.html", null ],
      [ "default_plan_options< backend::mkl_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl__cos_01_4.html", null ],
      [ "default_plan_options< backend::mkl_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl__sin_01_4.html", null ],
      [ "onemkl_executor", "classheffte_1_1onemkl__executor.html", "classheffte_1_1onemkl__executor" ],
      [ "onemkl_executor_r2c", "classheffte_1_1onemkl__executor__r2c.html", "classheffte_1_1onemkl__executor__r2c" ],
      [ "one_dim_backend< backend::onemkl >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl_01_4" ],
      [ "one_dim_backend< backend::onemkl_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__cos_01_4" ],
      [ "one_dim_backend< backend::onemkl_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__sin_01_4" ],
      [ "default_plan_options< backend::onemkl >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl_01_4.html", null ],
      [ "default_plan_options< backend::onemkl_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl__cos_01_4.html", null ],
      [ "default_plan_options< backend::onemkl_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl__sin_01_4.html", null ],
      [ "plan_rocfft", "structheffte_1_1plan__rocfft.html", "structheffte_1_1plan__rocfft" ],
      [ "plan_rocfft< std::complex< precision_type >, dir >", "structheffte_1_1plan__rocfft_3_01std_1_1complex_3_01precision__type_01_4_00_01dir_01_4.html", "structheffte_1_1plan__rocfft_3_01std_1_1complex_3_01precision__type_01_4_00_01dir_01_4" ],
      [ "rocfft_executor", "classheffte_1_1rocfft__executor.html", "classheffte_1_1rocfft__executor" ],
      [ "rocfft_executor_r2c", "classheffte_1_1rocfft__executor__r2c.html", "classheffte_1_1rocfft__executor__r2c" ],
      [ "one_dim_backend< backend::rocfft >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft_01_4" ],
      [ "one_dim_backend< backend::rocfft_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__cos_01_4" ],
      [ "one_dim_backend< backend::rocfft_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__sin_01_4" ],
      [ "default_plan_options< backend::rocfft >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft_01_4.html", null ],
      [ "default_plan_options< backend::rocfft_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft__cos_01_4.html", null ],
      [ "default_plan_options< backend::rocfft_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft__sin_01_4.html", null ],
      [ "is_ccomplex< stock::Complex< float, 1 > >", "structheffte_1_1is__ccomplex_3_01stock_1_1Complex_3_01float_00_011_01_4_01_4.html", null ],
      [ "is_zcomplex< stock::Complex< double, 1 > >", "structheffte_1_1is__zcomplex_3_01stock_1_1Complex_3_01double_00_011_01_4_01_4.html", null ],
      [ "plan_stock_fft", "structheffte_1_1plan__stock__fft.html", "structheffte_1_1plan__stock__fft" ],
      [ "plan_stock_fft< std::complex< F >, dir >", "structheffte_1_1plan__stock__fft_3_01std_1_1complex_3_01F_01_4_00_01dir_01_4.html", "structheffte_1_1plan__stock__fft_3_01std_1_1complex_3_01F_01_4_00_01dir_01_4" ],
      [ "stock_fft_executor", "classheffte_1_1stock__fft__executor.html", "classheffte_1_1stock__fft__executor" ],
      [ "stock_fft_executor_r2c", "classheffte_1_1stock__fft__executor__r2c.html", "classheffte_1_1stock__fft__executor__r2c" ],
      [ "one_dim_backend< backend::stock >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1stock_01_4" ],
      [ "one_dim_backend< backend::stock_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__cos_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__cos_01_4" ],
      [ "one_dim_backend< backend::stock_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__sin_01_4.html", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__sin_01_4" ],
      [ "default_plan_options< backend::stock >", "structheffte_1_1default__plan__options_3_01backend_1_1stock_01_4.html", null ],
      [ "default_plan_options< backend::stock_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1stock__cos_01_4.html", null ],
      [ "default_plan_options< backend::stock_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1stock__sin_01_4.html", null ],
      [ "executor_base", "classheffte_1_1executor__base.html", "classheffte_1_1executor__base" ],
      [ "one_dim_backend", "structheffte_1_1one__dim__backend.html", null ],
      [ "default_plan_options", "structheffte_1_1default__plan__options.html", null ],
      [ "fft_output", "structheffte_1_1fft__output.html", "structheffte_1_1fft__output" ],
      [ "fft_output< float >", "structheffte_1_1fft__output_3_01float_01_4.html", "structheffte_1_1fft__output_3_01float_01_4" ],
      [ "fft_output< double >", "structheffte_1_1fft__output_3_01double_01_4.html", "structheffte_1_1fft__output_3_01double_01_4" ],
      [ "transform_output", "structheffte_1_1transform__output.html", null ],
      [ "transform_output< scalar_type, backend_tag, typename std::enable_if< backend::uses_fft_types< backend_tag >::value >::type >", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab68ec9eb0046c8bf0dddff44974913856.html", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab68ec9eb0046c8bf0dddff44974913856" ],
      [ "transform_output< scalar_type, backend_tag, typename std::enable_if< not backend::uses_fft_types< backend_tag >::value >::type >", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab4657b516353cb2b2964ad38c40dce9ef.html", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab4657b516353cb2b2964ad38c40dce9ef" ],
      [ "fft3d", "classheffte_1_1fft3d.html", "classheffte_1_1fft3d" ],
      [ "fft3d_r2c", "classheffte_1_1fft3d__r2c.html", "classheffte_1_1fft3d__r2c" ],
      [ "box3d", "structheffte_1_1box3d.html", "structheffte_1_1box3d" ],
      [ "rank_remap", "structheffte_1_1rank__remap.html", "structheffte_1_1rank__remap" ],
      [ "ioboxes", "structheffte_1_1ioboxes.html", "structheffte_1_1ioboxes" ],
      [ "pack_plan_3d", "structheffte_1_1pack__plan__3d.html", "structheffte_1_1pack__plan__3d" ],
      [ "packer_backend", "structheffte_1_1packer__backend.html", null ],
      [ "direct_packer", "structheffte_1_1direct__packer.html", null ],
      [ "direct_packer< tag::cpu >", "structheffte_1_1direct__packer_3_01tag_1_1cpu_01_4.html", "structheffte_1_1direct__packer_3_01tag_1_1cpu_01_4" ],
      [ "transpose_packer", "structheffte_1_1transpose__packer.html", null ],
      [ "transpose_packer< tag::cpu >", "structheffte_1_1transpose__packer_3_01tag_1_1cpu_01_4.html", "structheffte_1_1transpose__packer_3_01tag_1_1cpu_01_4" ],
      [ "plan_options", "structheffte_1_1plan__options.html", "structheffte_1_1plan__options" ],
      [ "logic_plan3d", "structheffte_1_1logic__plan3d.html", "structheffte_1_1logic__plan3d" ],
      [ "cpu_cos_pre_pos_processor", "structheffte_1_1cpu__cos__pre__pos__processor.html", null ],
      [ "cpu_sin_pre_pos_processor", "structheffte_1_1cpu__sin__pre__pos__processor.html", null ],
      [ "real2real_executor", "structheffte_1_1real2real__executor.html", "structheffte_1_1real2real__executor" ],
      [ "reshape3d_base", "classheffte_1_1reshape3d__base.html", "classheffte_1_1reshape3d__base" ],
      [ "reshape3d_alltoall", "classheffte_1_1reshape3d__alltoall.html", "classheffte_1_1reshape3d__alltoall" ],
      [ "reshape3d_alltoallv", "classheffte_1_1reshape3d__alltoallv.html", "classheffte_1_1reshape3d__alltoallv" ],
      [ "reshape3d_pointtopoint", "classheffte_1_1reshape3d__pointtopoint.html", "classheffte_1_1reshape3d__pointtopoint" ],
      [ "reshape3d_transpose", "classheffte_1_1reshape3d__transpose.html", "classheffte_1_1reshape3d__transpose" ],
      [ "event", "structheffte_1_1event.html", "structheffte_1_1event" ],
      [ "add_trace", "structheffte_1_1add__trace.html", "structheffte_1_1add__trace" ],
      [ "is_ccomplex", "structheffte_1_1is__ccomplex.html", null ],
      [ "is_zcomplex", "structheffte_1_1is__zcomplex.html", null ],
      [ "is_ccomplex< std::complex< float > >", "structheffte_1_1is__ccomplex_3_01std_1_1complex_3_01float_01_4_01_4.html", null ],
      [ "is_zcomplex< std::complex< double > >", "structheffte_1_1is__zcomplex_3_01std_1_1complex_3_01double_01_4_01_4.html", null ],
      [ "define_standard_type", "structheffte_1_1define__standard__type.html", null ],
      [ "define_standard_type< float, void >", "structheffte_1_1define__standard__type_3_01float_00_01void_01_4.html", "structheffte_1_1define__standard__type_3_01float_00_01void_01_4" ],
      [ "define_standard_type< double, void >", "structheffte_1_1define__standard__type_3_01double_00_01void_01_4.html", "structheffte_1_1define__standard__type_3_01double_00_01void_01_4" ],
      [ "define_standard_type< scalar_type, typename std::enable_if< is_ccomplex< scalar_type >::value >::type >", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is9c0b841034586074be4b0a0e4b64ffb7.html", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is9c0b841034586074be4b0a0e4b64ffb7" ],
      [ "define_standard_type< scalar_type, typename std::enable_if< is_zcomplex< scalar_type >::value >::type >", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is686068e0b5e5f6d69fc4f745495aa74a.html", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is686068e0b5e5f6d69fc4f745495aa74a" ]
    ] ],
    [ "heffte_fft_plan", "structheffte__fft__plan.html", "structheffte__fft__plan" ],
    [ "heffte_plan_options", "structheffte__plan__options.html", "structheffte__plan__options" ]
];