var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "stock_fft", "dir_f08542d6236fc6a2005a48c92251774e.html", "dir_f08542d6236fc6a2005a48c92251774e" ],
    [ "heffte.h", "heffte_8h_source.html", null ],
    [ "heffte_backend_cuda.h", "heffte__backend__cuda_8h_source.html", null ],
    [ "heffte_backend_data_transfer.h", "heffte__backend__data__transfer_8h_source.html", null ],
    [ "heffte_backend_fftw.h", "heffte__backend__fftw_8h_source.html", null ],
    [ "heffte_backend_mkl.h", "heffte__backend__mkl_8h_source.html", null ],
    [ "heffte_backend_oneapi.h", "heffte__backend__oneapi_8h_source.html", null ],
    [ "heffte_backend_rocm.h", "heffte__backend__rocm_8h_source.html", null ],
    [ "heffte_backend_stock.h", "heffte__backend__stock_8h_source.html", null ],
    [ "heffte_backend_vector.h", "heffte__backend__vector_8h_source.html", null ],
    [ "heffte_backends.h", "heffte__backends_8h_source.html", null ],
    [ "heffte_c.h", "heffte__c_8h_source.html", null ],
    [ "heffte_c_defines.h", "heffte__c__defines_8h_source.html", null ],
    [ "heffte_common.h", "heffte__common_8h_source.html", null ],
    [ "heffte_compute_transform.h", "heffte__compute__transform_8h_source.html", null ],
    [ "heffte_config.cmake.h", "heffte__config_8cmake_8h_source.html", null ],
    [ "heffte_fft3d.h", "heffte__fft3d_8h_source.html", null ],
    [ "heffte_fft3d_r2c.h", "heffte__fft3d__r2c_8h_source.html", null ],
    [ "heffte_geometry.h", "heffte__geometry_8h_source.html", null ],
    [ "heffte_magma_helpers.h", "heffte__magma__helpers_8h_source.html", null ],
    [ "heffte_pack3d.h", "heffte__pack3d_8h_source.html", null ],
    [ "heffte_plan_logic.h", "heffte__plan__logic_8h_source.html", null ],
    [ "heffte_r2r_executor.h", "heffte__r2r__executor_8h_source.html", null ],
    [ "heffte_reshape3d.h", "heffte__reshape3d_8h_source.html", null ],
    [ "heffte_trace.h", "heffte__trace_8h_source.html", null ],
    [ "heffte_utils.h", "heffte__utils_8h_source.html", null ]
];