include("${CMAKE_CURRENT_LIST_DIR}/HEFFTE_Targets.cmake")

add_library(HEFFTE::FFTW INTERFACE IMPORTED GLOBAL)
target_link_libraries(HEFFTE::FFTW INTERFACE @FFTW_LIBRARIES@)
set_target_properties(HEFFTE::FFTW PROPERTIES INTERFACE_INCLUDE_DIRECTORIES @FFTW_INCLUDES@)
