var hierarchy =
[
    [ "heffte::add_trace", "structheffte_1_1add__trace.html", null ],
    [ "heffte::stock::biFuncNode< F, L >", "structheffte_1_1stock_1_1biFuncNode.html", null ],
    [ "heffte::box3d< index >", "structheffte_1_1box3d.html", null ],
    [ "heffte::backend::buffer_traits< backend_tag, type >", "structheffte_1_1backend_1_1buffer__traits.html", null ],
    [ "heffte::backend::buffer_traits< cufft >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft_01_4.html", null ],
    [ "heffte::backend::buffer_traits< cufft_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__cos_01_4.html", null ],
    [ "heffte::backend::buffer_traits< cufft_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01cufft__sin_01_4.html", null ],
    [ "heffte::backend::buffer_traits< onemkl >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl_01_4.html", null ],
    [ "heffte::backend::buffer_traits< onemkl_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__cos_01_4.html", null ],
    [ "heffte::backend::buffer_traits< onemkl_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01onemkl__sin_01_4.html", null ],
    [ "heffte::backend::buffer_traits< rocfft >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft_01_4.html", null ],
    [ "heffte::backend::buffer_traits< rocfft_cos >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__cos_01_4.html", null ],
    [ "heffte::backend::buffer_traits< rocfft_sin >", "structheffte_1_1backend_1_1buffer__traits_3_01rocfft__sin_01_4.html", null ],
    [ "heffte::stock::Complex< F, L >", "classheffte_1_1stock_1_1Complex.html", null ],
    [ "heffte::stock::complex_allocator_t< F >", "classheffte_1_1stock_1_1complex__allocator__t.html", null ],
    [ "heffte::cuda::cos_pre_pos_processor", "structheffte_1_1cuda_1_1cos__pre__pos__processor.html", null ],
    [ "heffte::oapi::cos_pre_pos_processor", "structheffte_1_1oapi_1_1cos__pre__pos__processor.html", null ],
    [ "heffte::rocm::cos_pre_pos_processor", "structheffte_1_1rocm_1_1cos__pre__pos__processor.html", null ],
    [ "heffte::tag::cpu", "structheffte_1_1tag_1_1cpu.html", null ],
    [ "heffte::cpu_cos_pre_pos_processor", "structheffte_1_1cpu__cos__pre__pos__processor.html", null ],
    [ "heffte::cpu_sin_pre_pos_processor", "structheffte_1_1cpu__sin__pre__pos__processor.html", null ],
    [ "heffte::backend::cufft", "structheffte_1_1backend_1_1cufft.html", null ],
    [ "heffte::backend::cufft_cos", "structheffte_1_1backend_1_1cufft__cos.html", null ],
    [ "heffte::backend::cufft_sin", "structheffte_1_1backend_1_1cufft__sin.html", null ],
    [ "heffte::backend::data_manipulator< location_tag >", "structheffte_1_1backend_1_1data__manipulator.html", null ],
    [ "heffte::backend::data_manipulator< tag::cpu >", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1cpu_01_4.html", null ],
    [ "heffte::backend::data_manipulator< tag::gpu >", "structheffte_1_1backend_1_1data__manipulator_3_01tag_1_1gpu_01_4.html", null ],
    [ "heffte::backend::default_backend< location_tag >", "structheffte_1_1backend_1_1default__backend.html", null ],
    [ "heffte::backend::default_backend< tag::cpu >", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1cpu_01_4.html", null ],
    [ "heffte::backend::default_backend< tag::gpu >", "structheffte_1_1backend_1_1default__backend_3_01tag_1_1gpu_01_4.html", null ],
    [ "heffte::default_plan_options< typename >", "structheffte_1_1default__plan__options.html", null ],
    [ "heffte::default_plan_options< backend::cufft >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft_01_4.html", null ],
    [ "heffte::default_plan_options< backend::cufft_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::cufft_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1cufft__sin_01_4.html", null ],
    [ "heffte::default_plan_options< backend::fftw >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw_01_4.html", null ],
    [ "heffte::default_plan_options< backend::fftw_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::fftw_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1fftw__sin_01_4.html", null ],
    [ "heffte::default_plan_options< backend::mkl >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl_01_4.html", null ],
    [ "heffte::default_plan_options< backend::mkl_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::mkl_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1mkl__sin_01_4.html", null ],
    [ "heffte::default_plan_options< backend::onemkl >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl_01_4.html", null ],
    [ "heffte::default_plan_options< backend::onemkl_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::onemkl_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1onemkl__sin_01_4.html", null ],
    [ "heffte::default_plan_options< backend::rocfft >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft_01_4.html", null ],
    [ "heffte::default_plan_options< backend::rocfft_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::rocfft_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1rocfft__sin_01_4.html", null ],
    [ "heffte::default_plan_options< backend::stock >", "structheffte_1_1default__plan__options_3_01backend_1_1stock_01_4.html", null ],
    [ "heffte::default_plan_options< backend::stock_cos >", "structheffte_1_1default__plan__options_3_01backend_1_1stock__cos_01_4.html", null ],
    [ "heffte::default_plan_options< backend::stock_sin >", "structheffte_1_1default__plan__options_3_01backend_1_1stock__sin_01_4.html", null ],
    [ "heffte::define_standard_type< typename, typename >", "structheffte_1_1define__standard__type.html", null ],
    [ "heffte::define_standard_type< double, void >", "structheffte_1_1define__standard__type_3_01double_00_01void_01_4.html", null ],
    [ "heffte::define_standard_type< float, void >", "structheffte_1_1define__standard__type_3_01float_00_01void_01_4.html", null ],
    [ "heffte::define_standard_type< scalar_type, typename std::enable_if< is_ccomplex< scalar_type >::value >::type >", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is9c0b841034586074be4b0a0e4b64ffb7.html", null ],
    [ "heffte::define_standard_type< scalar_type, typename std::enable_if< is_zcomplex< scalar_type >::value >::type >", "structheffte_1_1define__standard__type_3_01scalar__type_00_01typename_01std_1_1enable__if_3_01is686068e0b5e5f6d69fc4f745495aa74a.html", null ],
    [ "heffte::backend::device_instance< backend_tag >", "structheffte_1_1backend_1_1device__instance.html", null ],
    [ "heffte::backend::device_instance< backend::buffer_traits< backend_tag >::location >", "structheffte_1_1backend_1_1device__instance.html", [
      [ "heffte::fft3d< backend_tag, index >", "classheffte_1_1fft3d.html", null ],
      [ "heffte::fft3d_r2c< backend_tag, index >", "classheffte_1_1fft3d__r2c.html", null ]
    ] ],
    [ "heffte::backend::device_instance< location_tag >", "structheffte_1_1backend_1_1device__instance.html", [
      [ "heffte::reshape3d_alltoall< location_tag, packer, index >", "classheffte_1_1reshape3d__alltoall.html", null ],
      [ "heffte::reshape3d_alltoallv< location_tag, packer, index >", "classheffte_1_1reshape3d__alltoallv.html", null ],
      [ "heffte::reshape3d_pointtopoint< location_tag, packer, index >", "classheffte_1_1reshape3d__pointtopoint.html", null ],
      [ "heffte::reshape3d_transpose< location_tag, index >", "classheffte_1_1reshape3d__transpose.html", null ]
    ] ],
    [ "heffte::backend::device_instance< tag::gpu >", "structheffte_1_1backend_1_1device__instance_3_01tag_1_1gpu_01_4.html", null ],
    [ "heffte::backend::device_instance< typename heffte::backend::buffer_traits< fft_backend_tag >::location >", "structheffte_1_1backend_1_1device__instance.html", null ],
    [ "heffte::direct_packer< mode >", "structheffte_1_1direct__packer.html", null ],
    [ "heffte::direct_packer< tag::cpu >", "structheffte_1_1direct__packer_3_01tag_1_1cpu_01_4.html", null ],
    [ "heffte::direct_packer< tag::gpu >", "structheffte_1_1direct__packer_3_01tag_1_1gpu_01_4.html", null ],
    [ "heffte::event", "structheffte_1_1event.html", null ],
    [ "heffte::executor_base", "classheffte_1_1executor__base.html", [
      [ "heffte::cufft_executor", "classheffte_1_1cufft__executor.html", null ],
      [ "heffte::cufft_executor_r2c", "classheffte_1_1cufft__executor__r2c.html", null ],
      [ "heffte::fftw_executor", "classheffte_1_1fftw__executor.html", null ],
      [ "heffte::fftw_executor_r2c", "classheffte_1_1fftw__executor__r2c.html", null ],
      [ "heffte::mkl_executor", "classheffte_1_1mkl__executor.html", null ],
      [ "heffte::mkl_executor_r2c", "classheffte_1_1mkl__executor__r2c.html", null ],
      [ "heffte::onemkl_executor", "classheffte_1_1onemkl__executor.html", null ],
      [ "heffte::onemkl_executor_r2c", "classheffte_1_1onemkl__executor__r2c.html", null ],
      [ "heffte::real2real_executor< fft_backend_tag, prepost_processor >", "structheffte_1_1real2real__executor.html", null ],
      [ "heffte::rocfft_executor", "classheffte_1_1rocfft__executor.html", null ],
      [ "heffte::rocfft_executor_r2c", "classheffte_1_1rocfft__executor__r2c.html", null ],
      [ "heffte::stock_fft_executor", "classheffte_1_1stock__fft__executor.html", null ],
      [ "heffte::stock_fft_executor_r2c", "classheffte_1_1stock__fft__executor__r2c.html", null ]
    ] ],
    [ "std::false_type", null, [
      [ "heffte::backend::check_types< backend_tag, input, output, typename >", "structheffte_1_1backend_1_1check__types.html", null ],
      [ "heffte::backend::is_enabled< tag >", "structheffte_1_1backend_1_1is__enabled.html", null ],
      [ "heffte::backend::uses_fft_types< cufft_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01cufft__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< cufft_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01cufft__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< fftw_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01fftw__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< fftw_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01fftw__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< mkl_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01mkl__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< mkl_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01mkl__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< onemkl_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01onemkl__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< onemkl_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01onemkl__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< rocfft_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01rocfft__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< rocfft_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01rocfft__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< stock_cos >", "structheffte_1_1backend_1_1uses__fft__types_3_01stock__cos_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< stock_sin >", "structheffte_1_1backend_1_1uses__fft__types_3_01stock__sin_01_4.html", null ],
      [ "heffte::backend::uses_gpu< backend_tag, typename >", "structheffte_1_1backend_1_1uses__gpu.html", null ],
      [ "heffte::is_ccomplex< scalar_type >", "structheffte_1_1is__ccomplex.html", null ],
      [ "heffte::is_zcomplex< scalar_type >", "structheffte_1_1is__zcomplex.html", null ]
    ] ],
    [ "heffte::fft_output< scalar_type >", "structheffte_1_1fft__output.html", null ],
    [ "heffte::fft_output< double >", "structheffte_1_1fft__output_3_01double_01_4.html", null ],
    [ "heffte::fft_output< float >", "structheffte_1_1fft__output_3_01float_01_4.html", null ],
    [ "heffte::backend::fftw", "structheffte_1_1backend_1_1fftw.html", null ],
    [ "heffte::backend::fftw_cos", "structheffte_1_1backend_1_1fftw__cos.html", null ],
    [ "heffte::backend::fftw_sin", "structheffte_1_1backend_1_1fftw__sin.html", null ],
    [ "heffte::stock::Fourier_Transform< F, L >", "classheffte_1_1stock_1_1Fourier__Transform.html", null ],
    [ "heffte::tag::gpu", "structheffte_1_1tag_1_1gpu.html", null ],
    [ "heffte_fft_plan", "structheffte__fft__plan.html", null ],
    [ "heffte_plan_options", "structheffte__plan__options.html", null ],
    [ "heffte::ioboxes< index >", "structheffte_1_1ioboxes.html", null ],
    [ "heffte::stock::is_complex< T >", "structheffte_1_1stock_1_1is__complex.html", null ],
    [ "heffte::stock::is_real< T >", "structheffte_1_1stock_1_1is__real.html", null ],
    [ "heffte::logic_plan3d< index >", "structheffte_1_1logic__plan3d.html", null ],
    [ "heffte::gpu::magma_handle< typename >", "structheffte_1_1gpu_1_1magma__handle.html", null ],
    [ "heffte::gpu::magma_handle< tag::gpu >", "structheffte_1_1gpu_1_1magma__handle_3_01tag_1_1gpu_01_4.html", null ],
    [ "heffte::backend::mkl", "structheffte_1_1backend_1_1mkl.html", null ],
    [ "heffte::backend::mkl_cos", "structheffte_1_1backend_1_1mkl__cos.html", null ],
    [ "heffte::backend::mkl_sin", "structheffte_1_1backend_1_1mkl__sin.html", null ],
    [ "heffte::stock::omega< F, L >", "structheffte_1_1stock_1_1omega.html", null ],
    [ "heffte::one_dim_backend< typename >", "structheffte_1_1one__dim__backend.html", null ],
    [ "heffte::one_dim_backend< backend::cufft >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::cufft_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::cufft_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1cufft__sin_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::fftw >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::fftw_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::fftw_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1fftw__sin_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::mkl >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::mkl_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::mkl_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1mkl__sin_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::onemkl >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::onemkl_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::onemkl_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1onemkl__sin_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::rocfft >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::rocfft_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::rocfft_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1rocfft__sin_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::stock >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::stock_cos >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__cos_01_4.html", null ],
    [ "heffte::one_dim_backend< backend::stock_sin >", "structheffte_1_1one__dim__backend_3_01backend_1_1stock__sin_01_4.html", null ],
    [ "heffte::backend::onemkl", "structheffte_1_1backend_1_1onemkl.html", null ],
    [ "heffte::backend::onemkl_cos", "structheffte_1_1backend_1_1onemkl__cos.html", null ],
    [ "heffte::backend::onemkl_sin", "structheffte_1_1backend_1_1onemkl__sin.html", null ],
    [ "heffte::stock::pack< T, N >", "structheffte_1_1stock_1_1pack.html", null ],
    [ "heffte::stock::pack< double, 1 >", "structheffte_1_1stock_1_1pack_3_01double_00_011_01_4.html", null ],
    [ "heffte::stock::pack< F, L >", "structheffte_1_1stock_1_1pack.html", null ],
    [ "heffte::stock::pack< float, 1 >", "structheffte_1_1stock_1_1pack_3_01float_00_011_01_4.html", null ],
    [ "heffte::pack_plan_3d< index >", "structheffte_1_1pack__plan__3d.html", null ],
    [ "heffte::packer_backend< backend >", "structheffte_1_1packer__backend.html", null ],
    [ "heffte::plan_cufft< scalar_type >", "structheffte_1_1plan__cufft.html", null ],
    [ "heffte::plan_cufft_r2c< scalar_type >", "structheffte_1_1plan__cufft__r2c.html", null ],
    [ "heffte::plan_fftw< typename, direction >", "structheffte_1_1plan__fftw.html", null ],
    [ "heffte::plan_fftw< double, dir >", "structheffte_1_1plan__fftw_3_01double_00_01dir_01_4.html", null ],
    [ "heffte::plan_fftw< float, dir >", "structheffte_1_1plan__fftw_3_01float_00_01dir_01_4.html", null ],
    [ "heffte::plan_fftw< std::complex< double >, dir >", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01double_01_4_00_01dir_01_4.html", null ],
    [ "heffte::plan_fftw< std::complex< float >, dir >", "structheffte_1_1plan__fftw_3_01std_1_1complex_3_01float_01_4_00_01dir_01_4.html", null ],
    [ "heffte::plan_mkl< scalar_type >", "structheffte_1_1plan__mkl.html", null ],
    [ "heffte::plan_mkl_r2c< scalar_type, dir >", "structheffte_1_1plan__mkl__r2c.html", null ],
    [ "heffte::plan_options", "structheffte_1_1plan__options.html", null ],
    [ "heffte::plan_rocfft< precision_type, dir >", "structheffte_1_1plan__rocfft.html", null ],
    [ "heffte::plan_rocfft< std::complex< precision_type >, dir >", "structheffte_1_1plan__rocfft_3_01std_1_1complex_3_01precision__type_01_4_00_01dir_01_4.html", null ],
    [ "heffte::plan_stock_fft< F, dir >", "structheffte_1_1plan__stock__fft.html", null ],
    [ "heffte::plan_stock_fft< std::complex< F >, dir >", "structheffte_1_1plan__stock__fft_3_01std_1_1complex_3_01F_01_4_00_01dir_01_4.html", null ],
    [ "heffte::rank_remap", "structheffte_1_1rank__remap.html", null ],
    [ "heffte::stock::complex_allocator_t< F >::rebind< U >", "structheffte_1_1stock_1_1complex__allocator__t_1_1rebind.html", null ],
    [ "heffte::reshape3d_base< index >", "classheffte_1_1reshape3d__base.html", [
      [ "heffte::reshape3d_alltoall< location_tag, packer, index >", "classheffte_1_1reshape3d__alltoall.html", null ],
      [ "heffte::reshape3d_alltoallv< location_tag, packer, index >", "classheffte_1_1reshape3d__alltoallv.html", null ],
      [ "heffte::reshape3d_pointtopoint< location_tag, packer, index >", "classheffte_1_1reshape3d__pointtopoint.html", null ],
      [ "heffte::reshape3d_transpose< location_tag, index >", "classheffte_1_1reshape3d__transpose.html", null ]
    ] ],
    [ "heffte::backend::rocfft", "structheffte_1_1backend_1_1rocfft.html", null ],
    [ "heffte::backend::rocfft_cos", "structheffte_1_1backend_1_1rocfft__cos.html", null ],
    [ "heffte::backend::rocfft_sin", "structheffte_1_1backend_1_1rocfft__sin.html", null ],
    [ "heffte::cuda::sin_pre_pos_processor", "structheffte_1_1cuda_1_1sin__pre__pos__processor.html", null ],
    [ "heffte::oapi::sin_pre_pos_processor", "structheffte_1_1oapi_1_1sin__pre__pos__processor.html", null ],
    [ "heffte::rocm::sin_pre_pos_processor", "structheffte_1_1rocm_1_1sin__pre__pos__processor.html", null ],
    [ "heffte::backend::stock", "structheffte_1_1backend_1_1stock.html", null ],
    [ "heffte::backend::stock_cos", "structheffte_1_1backend_1_1stock__cos.html", null ],
    [ "heffte::backend::stock_sin", "structheffte_1_1backend_1_1stock__sin.html", null ],
    [ "heffte::transform_output< scalar_type, backend_tag, typename >", "structheffte_1_1transform__output.html", null ],
    [ "heffte::transform_output< scalar_type, backend_tag, typename std::enable_if< backend::uses_fft_types< backend_tag >::value >::type >", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab68ec9eb0046c8bf0dddff44974913856.html", null ],
    [ "heffte::transform_output< scalar_type, backend_tag, typename std::enable_if< not backend::uses_fft_types< backend_tag >::value >::type >", "structheffte_1_1transform__output_3_01scalar__type_00_01backend__tag_00_01typename_01std_1_1enab4657b516353cb2b2964ad38c40dce9ef.html", null ],
    [ "heffte::transpose_packer< mode >", "structheffte_1_1transpose__packer.html", null ],
    [ "heffte::transpose_packer< tag::cpu >", "structheffte_1_1transpose__packer_3_01tag_1_1cpu_01_4.html", null ],
    [ "heffte::transpose_packer< tag::gpu >", "structheffte_1_1transpose__packer_3_01tag_1_1gpu_01_4.html", null ],
    [ "std::true_type", null, [
      [ "heffte::backend::check_types< backend_tag, input, output, typename std::enable_if< not uses_fft_types< backend_tag >::value and((std::is_same< input, float >::value and std::is_same< output, float >::value) or(std::is_same< input, double >::value and std::is_same< output, double >::value))>::type >", "structheffte_1_1backend_1_1check__types_3_01backend__tag_00_01input_00_01output_00_01typename_01f9006ec2132705c3597d1dc98451f7b8.html", null ],
      [ "heffte::backend::check_types< backend_tag, input, output, typename std::enable_if< uses_fft_types< backend_tag >::value and((std::is_same< input, float >::value and is_ccomplex< output >::value) or(std::is_same< input, double >::value and is_zcomplex< output >::value) or(is_ccomplex< input >::value and is_ccomplex< output >::value) or(is_zcomplex< input >::value and is_zcomplex< output >::value))>::type >", "structheffte_1_1backend_1_1check__types_3_01backend__tag_00_01input_00_01output_00_01typename_01c412e8b081eebe81d371306e70d2da56.html", null ],
      [ "heffte::backend::is_enabled< cufft >", "structheffte_1_1backend_1_1is__enabled_3_01cufft_01_4.html", null ],
      [ "heffte::backend::is_enabled< cufft_cos >", "structheffte_1_1backend_1_1is__enabled_3_01cufft__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< cufft_sin >", "structheffte_1_1backend_1_1is__enabled_3_01cufft__sin_01_4.html", null ],
      [ "heffte::backend::is_enabled< fftw >", "structheffte_1_1backend_1_1is__enabled_3_01fftw_01_4.html", null ],
      [ "heffte::backend::is_enabled< fftw_cos >", "structheffte_1_1backend_1_1is__enabled_3_01fftw__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< fftw_sin >", "structheffte_1_1backend_1_1is__enabled_3_01fftw__sin_01_4.html", null ],
      [ "heffte::backend::is_enabled< mkl >", "structheffte_1_1backend_1_1is__enabled_3_01mkl_01_4.html", null ],
      [ "heffte::backend::is_enabled< mkl_cos >", "structheffte_1_1backend_1_1is__enabled_3_01mkl__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< mkl_sin >", "structheffte_1_1backend_1_1is__enabled_3_01mkl__sin_01_4.html", null ],
      [ "heffte::backend::is_enabled< onemkl >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl_01_4.html", null ],
      [ "heffte::backend::is_enabled< onemkl_cos >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< onemkl_sin >", "structheffte_1_1backend_1_1is__enabled_3_01onemkl__sin_01_4.html", null ],
      [ "heffte::backend::is_enabled< rocfft >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft_01_4.html", null ],
      [ "heffte::backend::is_enabled< rocfft_cos >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< rocfft_sin >", "structheffte_1_1backend_1_1is__enabled_3_01rocfft__sin_01_4.html", null ],
      [ "heffte::backend::is_enabled< stock >", "structheffte_1_1backend_1_1is__enabled_3_01stock_01_4.html", null ],
      [ "heffte::backend::is_enabled< stock_cos >", "structheffte_1_1backend_1_1is__enabled_3_01stock__cos_01_4.html", null ],
      [ "heffte::backend::is_enabled< stock_sin >", "structheffte_1_1backend_1_1is__enabled_3_01stock__sin_01_4.html", null ],
      [ "heffte::backend::uses_fft_types< backend_tag >", "structheffte_1_1backend_1_1uses__fft__types.html", null ],
      [ "heffte::backend::uses_gpu< backend_tag, typename std::enable_if< std::is_same< typename buffer_traits< backend_tag >::location, tag::gpu >::value, void >::type >", "structheffte_1_1backend_1_1uses__gpu_3_01backend__tag_00_01typename_01std_1_1enable__if_3_01std_6bad166a1b2e2b72cd8ee197f3565dff.html", null ],
      [ "heffte::is_ccomplex< cufftComplex >", "structheffte_1_1is__ccomplex_3_01cufftComplex_01_4.html", null ],
      [ "heffte::is_ccomplex< fftwf_complex >", "structheffte_1_1is__ccomplex_3_01fftwf__complex_01_4.html", null ],
      [ "heffte::is_ccomplex< float _Complex >", "structheffte_1_1is__ccomplex_3_01float_01__Complex_01_4.html", null ],
      [ "heffte::is_ccomplex< std::complex< float > >", "structheffte_1_1is__ccomplex_3_01std_1_1complex_3_01float_01_4_01_4.html", null ],
      [ "heffte::is_ccomplex< stock::Complex< float, 1 > >", "structheffte_1_1is__ccomplex_3_01stock_1_1Complex_3_01float_00_011_01_4_01_4.html", null ],
      [ "heffte::is_zcomplex< cufftDoubleComplex >", "structheffte_1_1is__zcomplex_3_01cufftDoubleComplex_01_4.html", null ],
      [ "heffte::is_zcomplex< double _Complex >", "structheffte_1_1is__zcomplex_3_01double_01__Complex_01_4.html", null ],
      [ "heffte::is_zcomplex< fftw_complex >", "structheffte_1_1is__zcomplex_3_01fftw__complex_01_4.html", null ],
      [ "heffte::is_zcomplex< std::complex< double > >", "structheffte_1_1is__zcomplex_3_01std_1_1complex_3_01double_01_4_01_4.html", null ],
      [ "heffte::is_zcomplex< stock::Complex< double, 1 > >", "structheffte_1_1is__zcomplex_3_01stock_1_1Complex_3_01double_00_011_01_4_01_4.html", null ]
    ] ]
];